# The COPYRIGHT file at the top level of this repository contains
# the full copyright notices and license terms.
from trytond.pool import Pool
from. import party
from. import welding
from . import configuration
from. import bewertung
from .welding import ZertifikatIso96061Report
from .bewertung import ZertifikatBewertungReport
__all__ = ['register','ZertifikatIso96061Report','ZertifikatBewertungReport','ZertifikatBewertungIso5817Report']
def register():
    Pool.register(
        party.Party,
        party.PartyBriefing,
        party.PartyOccupationalCheckup,
        party.PartyProfession,
        party.wps,
        party.Party_wolframelektrodenart,
        party.Party_wolframelektrodenart2,
        party.iso14732,
        party.PrintISO96061Start,
        party.UploadxmlStart,
        party.PrintWPSStart,
        party.iso96062,
        party.Datumm,
        party.PrintENISO96062Start,
        party.Datumm5_3,
        party.Datumm5,
        party.PrintENISO14732Start,
        party.Bewertung2,
        party.PrintISONORMES,
        party.wpqr,
        party.schutzgaswpqr,
        party.PrintISOWPQRStart,
        party.wpqrbericht1,
        party.prufergebnisse,
        party.Querzugversuch,
        party.Biegepruf,
        party.kerbschlabiegeversuch1,
        party.wpqrbericht2,
        party.Harteprufung,
        party.Harteprufung1,
        party.wpqr2,
        party.hubzundungs,
        party.PrintISOWPQR2Start,
        party.wpqr3,
        party.PrintISOWPQR3Start,
        party.wpqr4,
        party.kondersatorentladungs,
        party.PrintISOWPQR4Start,
        party.wpqr5,
        party.PrintISOWPQR5Start,
        party.wpqr6,
        party.fm1,
        party.PrintISOWPQR6Start,
        party.qw483,
        party.tensile,
        party.guidedbend,
        party.toughness,
        party.listeneintrag,
        party.zfptp,
        party.PrintZfPStart,
        party.WOPQ,
        party.PNumber,
        party.SFA,
        party.WPQResults,
        party.PrintWPQStart,
        party.WOPQ2,
        party.UNS,
        party.WOPQResults,
        party.PrintWOPQStart,
        party.process,
        party.pruf_prufstelle_Beleg_nr,
        welding.SchweißanweisungWps,
        welding.Iso96061,
        welding.Tropfenuebergang,
        welding.WeldingClass,
        welding.GrundwerkstoffProperties,
        welding.SchweißanweisungWpsEinzelheitenSchweissen,
        welding.WolframelektrodenartData,
        welding.Wolframelektrodenart2Properties,
        welding.WpqrNr,
        welding.ProcessIso4063,
        welding.Erzeugnis,
        welding.SziData,
        welding.SchweisspositionIso6947,
        welding.NahtNr,
        welding.Schweisszusatz,
        welding.ListGasMischgase,
        welding.BildsProperties,
        welding.SchweißfolgenProperties,
        welding.Hinweise,
        welding.Pruefstelle,
        welding.WerkstoffgruppeSchweißzusatz,
        welding.Schweißprozesse,
        welding.WeldingDatumms,
        welding.QualifikationDatumms,
        bewertung.Bewertung,
        bewertung.BewertungIso5817,       
        bewertung.BewertungSichtprüfungDecklage,
        bewertung.BewertungSichtprüfungKehlnaht,
        bewertung.BewertungDurchstrahlungsprüfung,
        bewertung.BewertungBruchprüfung,
        bewertung.BewertungBiegeprüfung,
        bewertung.BewertungWeiterePrüfung,
        configuration.Configuration,
        configuration.ConfigurationSequence,
        module='welding_certification', type_='model')
    Pool.register(
        party.PrintISO96061,
        party.uploadxlsISO96061,
        party.PrintWPS,
        party.PrintISO96062,
        party.PrintISO14732,
        party.PrintWPQR,
        party.PrintWPQR2,
        party.PrintWPQR3,
        party.PrintWPQR4,
        party.PrintWPQR5,
        party.PrintWPQR6,
        party.PrintZfP,
        party.PrintWPQ,
        party.PrintWOPQ,
        module='welding_certification', type_='wizard')
    Pool.register(
        party.ISOWPSreport,
        party.ISO96061report,
        party.ISO96062report,
        party.ISO14732report,
        party.ISONORMESreport,
        party.ISOWPQRreport,
        party.Bericht1report,
        party.Bericht2report,
        party.ISOWPQR2report,
        party.ISOWPQR3report,
        party.ISOWPQR4report,
        party.ISOWPQR5report,
        party.ISOWPQR6report,
        party.wq483report,
        party.ZfPreport,
        party.WPQreport,
        party.WOPQreport,
        welding.SchweißanweisungWpsReport,
        welding.Iso96061Report,
        bewertung.BewertungReport,       
        bewertung.BewertungIso5817Report,                 
        module='welding_certification', type_='report')
